#ifndef SOURCE_CLASS_DISPLAYENTITY_DRAWOBJECT_DRAWOBJECTENTITY_H_
#define SOURCE_CLASS_DISPLAYENTITY_DRAWOBJECT_DRAWOBJECTENTITY_H_

class DrawObjectEntity {
public:
	DrawObjectEntity();
	virtual ~DrawObjectEntity();


};

#endif /* SOURCE_CLASS_DISPLAYENTITY_DRAWOBJECT_DRAWOBJECTENTITY_H_ */
